training:
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.0001
  dropout_rate: 0.5
  
uncertainty:
  method: "mc_dropout"
  threshold: 0.4
  num_samples: 10

data:
  img_size: 224
  max_samples: null  # Use full dataset